nodeSelector:
  kubernetes.io/hostname: t2-1

securityContext:
  runAsNonRoot: true
  runAsUser: 1001

tolerations:
- key: "cnaps.io/node-taint"
  operator: "Equal"
  value: "noncore"
  effect: "NoSchedule"